baseURL: https://minwoo.kim/
disablePathToLower: true
languageCode: ko-kr
title: 'minwoo.kim'
googleAnalytics: 'G-NNJRMRDR0M'
enableRobotsTXT: true
theme: PaperMod
params:
  homeInfoParams:
    Title: ì•ˆë…•í•˜ì„¸ìš”! ğŸ™‹
    Content: |
      ê°œë°œ, í´ë¼ìš°ë“œ ë° ì»¨í…Œì´ë„ˆ ë“±ì„ ì •ë¦¬í•˜ëŠ” ê¸°ìˆ  ë¸”ë¡œê·¸ì…ë‹ˆë‹¤.
  socialIcons:
    - name: 'github'
      url: 'https://github.com/minuchi'
    - name: 'email'
      url: 'mailto:me@minwoo.kim'
  env: 'production'
  description: 'ê°œë°œ, í´ë¼ìš°ë“œ ë° ì»¨í…Œì´ë„ˆ ë“±ì„ ì •ë¦¬í•˜ëŠ” ê¸°ìˆ  ë¸”ë¡œê·¸ì…ë‹ˆë‹¤.'
  images: ['/assets/img/banner.png']
  analytics:
    google:
      SiteVerificationTag: 'CJVLd1xPaZ7Df3oS7VfZDAFaMTcdYqlO0XQkfRKQ1yk'
  comments: true
